### ISSUE TITLE
unnecessary call to `observable.complete`

### ISSUE THREAD

**Issue by jamestalmage** [jamestalmage/stream-to-observable#4]
should do `completion.then(..).catch(..)` instead of existing reverse order.

See @novemberborn's comment in #1

**Comment by novemberborn** [comment]
You could combine the catch callback (`completion.then(…, …)`).

**Comment by jamestalmage** [comment]
http://bluebirdjs.com/docs/anti-patterns.html#the-.then

**Comment by novemberborn** [comment]
Meh, you don't need to catch errors from the first `.then()`.
